# Generated by Django 5.0.2 on 2025-04-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_customuser_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_manage_users', 'Puede gestionar usuarios'), ('can_create_projects', 'Puede crear proyectos'), ('can_view_analytics', 'Puede ver análisis')], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
    ]
