# Generated by Django 5.0.2 on 2025-04-08 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('requirements', models.TextField(verbose_name='Requisitos')),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario mínimo')),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salario máximo')),
                ('employment_type', models.CharField(choices=[('full_time', 'Tiempo Completo'), ('part_time', 'Tiempo Parcial'), ('contract', 'Contrato'), ('temporary', 'Temporal'), ('internship', 'Prácticas')], max_length=20, verbose_name='Tipo de empleo')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('external_id', models.CharField(blank=True, help_text='ID de la oferta en el sistema externo', max_length=100, verbose_name='ID Externa')),
                ('url', models.URLField(blank=True, verbose_name='URL de la oferta')),
                ('skills', models.ManyToManyField(related_name='job_offers', to='data_integration.skill', verbose_name='Habilidades requeridas')),
            ],
            options={
                'verbose_name': 'Oferta de Trabajo',
                'verbose_name_plural': 'Ofertas de Trabajo',
                'ordering': ['-date_posted'],
                'indexes': [models.Index(fields=['title', 'company'], name='data_integr_title_3beba8_idx'), models.Index(fields=['location'], name='data_integr_locatio_b1f413_idx'), models.Index(fields=['date_posted'], name='data_integr_date_po_4dc849_idx')],
            },
        ),
    ]
